version: '3.8'

services:
  app:
    container_name: python-script
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c 'sleep 5 && python -u file_sizes_data.py'

  db:
    container_name: database
    image: postgres:13
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env

volumes:
  postgres-data:
